source 'https://rubygems.org'

gem 'activerecord'
gem 'database_cleaner'
gem 'factory_girl'
gem 'growl'
gem 'guard'
gem 'guard-rspec'
gem 'rspec'
gem 'sqlite3'
gem 'terminal-notifier'
gem 'terminal-notifier-guard'
gem 'rack-test'
gem 'sinatra'
gem 'rack-mini-profiler'
